### ISSUE TITLE
i think that the member variable locked in QNode need declare as volatile

### ISSUE THREAD

**Issue by fengshuu** [javaf/clh-lock#1]
like that

```java
public class QNode {
    volatile boolean locked = false;
}
```

**Comment by wolfram77** [comment]
@fengshuu 

I think you are right as otherwise it should get stuck in `while(m.locked) Thread.yield();` loop.

However on running it, both with and without `volatile`, observed no difference. Maybe this because the while-loop is not busy check, but with `Thread.yield()`. So every time the thread is resumed, it performs the memory access.

It is nice to think about think about multithread sometimes, thanks for your suggestion.
